config/routes.rb
Plymlet::Application.routes.draw do

  root :to => 'static_pages#home'

  devise_for :users 
  resources :passages do
    post :add_to_vocab_list, :on => :collection 
    post :remove_from_vocab_list, :on => :collection 
  end

  resources :users, :only => [:index, :show]

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
end

app/models/passage.rb
# == Schema Information
#
# Table name: passages
#
#  id         :integer         not null, primary key
#  passage_id :integer
#  title      :string(255)
#  author     :string(255)
#  language   :string(255)
#  content    :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Passage < ActiveRecord::Base
  attr_accessible :author, :content, :language, :title

  serialize :vocab_list, ActiveRecord::Coders::Hstore

  after_initialize :add_empty_hash

  def add_empty_hash
    self.vocab_list ||= {}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  validates_presence_of :username
  validates_uniqueness_of :username

  serialize :vocab_list, ActiveRecord::Coders::Hstore

  after_initialize :add_empty_hash

  def add_empty_hash
    self.vocab_list ||= {}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    passages_path
  end

end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @passages = Passage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passages }
    end
  end

  def show
    @passage = Passage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @passage }
    end
  end

  def new
    @passage = Passage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @passage }
    end
  end

  def edit
    @passage = Passage.find(params[:id])
  end

  def create
    @passage = Passage.new(params[:passage])

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render json: @passage, status: :created, location: @passage }
      else
        format.html { render action: "new" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @passage = Passage.find(params[:id])

    respond_to do |format|
      if @passage.update_attributes(params[:passage])
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy

    respond_to do |format|
      format.html { redirect_to passages_url }
      format.json { head :no_content }
    end
  end

  def add_to_vocab_list
    current_user.vocab_list[params[:vocab_word]] = params[:vocab_def]
    current_user.save
    redirect_to :back, :notice => "Word successfully saved."
  end

  def remove_from_vocab_list
    current_user.vocab_list.delete params[:vocab_word]
    current_user.save
    redirect_to :back, :notice => "Word removed."
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :authenticate_user!

def index
  @users = User.paginate(page: params[:page])
end

def show
  @user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passages_helper.rb
module PassagesHelper

  def unique_words(content)
    @words = content.downcase.gsub(/[[:punct:]]/,"").split(' ').uniq
  end

  def all_words(content)
   # @words = content.downcase.gsub(/[[:punct:]]/,"").split(' ')
    @words = content.downcase.gsub(/[[:punct:]]/){|p| " " + p + " " }.split(' ')
  end

# this method is only for looking up in CEDICT, Redis should be used later after rake
  def define_word_CEDICT(word)
    @cedict = 'cedict.txt'
    @word_matches = File.readlines(@cedict).grep(/#{word}/)

    @best_match = []

    @word_matches.each do |x|
      # CEDICT lists simplified and traditional characters, space delimited
      # 学 = "學 学 [xue2] /to learn/to study/science/-ology/"
      @match = x.split

      if @match[0] == word || @match[1] == word
        @best_match << x
      end
    end

    return @best_match
  end

# this method is only for looking up in EDICT, Redis should be used later after rake
  def define_word_EDICT(word)
    @edict = 'edict2utf8'
    @word_matches = File.readlines(@edict).grep(/#{word}/)

     @best_match = []
 
     @word_matches.each do |x|
       @match = x.split(/[ ()\[\];]/)
 
       if @match[0] == word || @match[1] == word || @match[2] == word || @match[3] == word
         @best_match << x
       end
     end
 
     return @best_match
  end

# rake passage_defs for this to work
  def define_word(word)
    REDIS.lrange(word, 0, -1)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Plymlet", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    passages_path %></li>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "My Account", current_user %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Plymlet | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <% end %>
</head>

<body>

<%= render 'layouts/header' %>

<div class="container">
<%= yield %>
</div>

<% if user_signed_in? %>
  <%= render 'layouts/footer' %>
<% end %>

</body>
</html>

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passages/_tabs.html.erb
<div id="tabs">
    <ul>
        <li>
            <a href="#tabs-1">Definition</a>
        </li>
        <li>
            <a href="#tabs-2">Vocabulary List</a>
        </li>
    </ul>

    <div id="tabs-1">
        <p>Hi!</p>
    </div>
    <div id="tabs-2">
        <p>Where?</p>
    </div>
</div>

app/views/passages/edit.html.erb
<%= provide(:title, "Edit Passage") %>
<div class="container">
<h1>Editing passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>
</div>

app/views/passages/index.html.erb
<%= provide(:title, "Passages") %>
<div class="container">
<h1>Listing passages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @passages.each do |passage| %>
  <tr>
    <td><%= passage.title %></td>
    <td><%= passage.author %></td>
    <td><%= passage.language %></td>
    <td><%= link_to 'Show', passage %></td>
    <td><%= link_to 'Edit', edit_passage_path(passage) %></td>
    <td><%= link_to 'Destroy', passage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Passage', new_passage_path %>
</div>

app/views/passages/new.html.erb
<%= provide(:title, "New Passage") %>
<div class="container">
<h1>New passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>
</div>

app/views/passages/show.html.erb
<%= provide(:title, @passage.title) %>

<% content_for :for_head do %>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<% end %>

<p id="notice"><%= notice %></p>

<div id="leftcol">
  <div class="passage">
    <p class="passage-info"><span class="boldme">Title:</span> <%= @passage.title %></p>
    <p class="passage-info"><span class="boldme">Author:</span> <%= @passage.author %></p>
    <p class="passage-info"><span class="boldme">Language:</span> <%= @passage.language %></p>
    <p><% all_words(@passage.content).each do |x| %>
      <span class="passage-word"><a href="#"><%= x %></a></span> 
    <% end %>
    </p>
    <p class="passage-info"><%= link_to 'Edit', edit_passage_path(@passage) %> |
    <%= link_to 'Back', passages_path %>
    </p>
  </div>
</div>

<div id="rightcol">
  <div class="author-notes">

  </div>

  <div class="inline"><span class="passage-word"><p class="btn btn-primary">Show All Words</p></span></div>
  <div class="inline"><span class="passage-word"><p class="btn btn-primary">Hide My Words</p></span></div>

  <div id="vocab-box">
    <ul class="vocab-list"><% @passage.vocab_list.each do |key, value| %>
        <li class="vocab-item">
          <p class="vocab-word"><%= key %></p>
            <% if current_user.vocab_list.has_key?(key) %>
              <%= button_to "Remove from My Words", remove_from_vocab_list_passages_path(:vocab_word => key), :class => "btn btn-warning" %>
            <% else %>
              <%= button_to "Add to My Words", add_to_vocab_list_passages_path(:vocab_word => key, :vocab_def => value), :class => "btn btn-primary" %>
            <% end %>
          <p class="vocab-def"><%= value %></p>
        </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>

<h1>About Plymlet</h1>
<p>This is a project I have been working on part-time over a few years based on my language learning hobby. I hope other learners find it useful!</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>

<h1>Contact Information:</h1>
<p>Email:</p>
<li>test@test.com</li>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>

<h1>Help</h1>
<p>Help is on the way!</p>

app/views/static_pages/home.html.erb
<%= provide(:title, "Home") %>

<div class="hero-unit">
  <h1>Welcome to Plymlet!</h1>
  <h2>We are an online language learning platform.</h2>
  <h3>Our approach is threefold:</h3>
  <div class="ul-container">
    <ul>
      <li>Discover and organize what you know</li>
      <li>Match you with content appropriate for your level</li>
      <li>Connect you with content authors, teachers, and other students</li>
    </ul>  
</div>
<div class="center container">
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.email, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<%= provide(:title, "Profile") %>
<% content_for :for_head do %>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<% end %>

<p id="notice"><%= notice %></p>

<div id="leftcol" style="width:10%">
  <%= gravatar_for @user %>
  <h3><%= @user.username %></h3>
</div>
<div id="ctrcol">
  <div class="ul-container">
    <ul>
      <h2>Account Details</h2>
      <li>Username: <%= @user.username %></li>
      <li>Email: <%= @user.email %></li>
      <% if @user == current_user %>
        <%= link_to "Edit User Information", edit_user_registration_path %>
      <% end %>
    </ul>
  </div>
</div>

<div id="rightcol">
  <p>My Words</p>
  <div id="vocab-box">
    <ul class="vocab-list"><% @user.vocab_list.each do |key,value| %>
      <% begin %>
        <li class="vocab-item">
          <p class="vocab-word"><%= key %></p>
            <% if @user == current_user %>
              <%= button_to "Remove from My Words", remove_from_vocab_list_passages_path(:vocab_word => key), :class => "btn btn-warning", :confirm => "Are you sure?" %>
            <% end %>
          <p class="vocab-def"><%= value %></p>
        </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>